apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-sample-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-sample
  template:
    metadata:
      labels:
        app: nodejs-sample
    spec:
      containers:
        - name: nodejs-sample
          image: nodejs-app:latest
          ports:
            - containerPort: 3000

